input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate { add_field => { "service" => "unknown" } }
  }
  if ![environment] {
    mutate { add_field => { "environment" => "local" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "project15-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
